DEVICES = [
    {
        "SWITCH_IP": "12.0.96.253",
        "Device_name": "政务外网出口防火墙USG12004-01",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.96.254",
        "Device_name": "政务外网出口防火墙USG12004-02",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.96.251",
        "Device_name": "政务外网管理防火墙-01",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.96.252",
        "Device_name": "政务外网管理防火墙-02",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.96.253",
        "Device_name": "互联网出口防火墙USG12004-01",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.96.254",
        "Device_name": "互联网出口防火墙USG12004-02",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.96.251",
        "Device_name": "互联网管理防火墙-01",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.96.252",
        "Device_name": "互联网管理防火墙-02",
        "device_type": "huawei",
        "USERNAME": "libaokui",
        "PASSWORD": "Wxxcy$%2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.2",
        "Device_name": "政务外网出口路由器NE8000M-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.3",
        "Device_name": "政务外网出口路由器NE8000M-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.4",
        "Device_name": "政务外网数据中心核心CE16808-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.5",
        "Device_name": "政务外网数据中心核心CE16808-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.6",
        "Device_name": "政务外网华三安全资源池接入-01",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.7",
        "Device_name": "政务外网华三安全资源池接入-02",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.2",
        "Device_name": "政务外网边界网关节点-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.3",
        "Device_name": "政务外网边界网关节点-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.4",
        "Device_name": "政务外网L3GW-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.5",
        "Device_name": "政务外网L3GW-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.6",
        "Device_name": "政务外网云内核心交换机-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.7",
        "Device_name": "政务外网云内核心交换机-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.2",
        "Device_name": "互联网出口路由器NE8000M-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.3",
        "Device_name": "互联网出口路由器NE8000M-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.4",
        "Device_name": "互联网数据中心核心CE16808-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.5",
        "Device_name": "互联网数据中心核心CE16808-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.6",
        "Device_name": "互联网华三安全资源池接入-01",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.7",
        "Device_name": "互联网华三安全资源池接入-02",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.2",
        "Device_name": "互联网边界网关节点-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.3",
        "Device_name": "互联网边界网关节点-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.4",
        "Device_name": "互联网L3GW-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.5",
        "Device_name": "互联网L3GW-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.6",
        "Device_name": "互联网云内核心交换机-01",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.7",
        "Device_name": "互联网云内核心交换机-02",
        "device_type": "huawei",
        "USERNAME": "huawei",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.12",
        "Device_name": "政务外网管理区管理接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.13",
        "Device_name": "政务外网管理区管理接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.14",
        "Device_name": "政务外网备份接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.15",
        "Device_name": "政务外网备份接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.16",
        "Device_name": "政务外网BMC接入交换机S5130（堆叠）",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.17",
        "Device_name": "政务外网业务汇聚交换机S9850-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.18",
        "Device_name": "政务外网业务汇聚交换机S9850-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.23",
        "Device_name": "政务外网网络接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.24",
        "Device_name": "政务外网网络接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.19",
        "Device_name": "政务外网业务接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.20",
        "Device_name": "政务外网业务接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.21",
        "Device_name": "政务外网计算节点存储接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.22",
        "Device_name": "政务外网计算节点存储接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.25",
        "Device_name": "政务外网存储汇聚交换机S9850-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.26",
        "Device_name": "政务外网存储汇聚交换机S9850-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.27",
        "Device_name": "政务外网存储前端交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.28",
        "Device_name": "政务外网存储前端交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.29",
        "Device_name": "政务外网存储后端交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.30",
        "Device_name": "政务外网存储后端交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.31",
        "Device_name": "政务外网OBS接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.32",
        "Device_name": "政务外网OBS接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.33",
        "Device_name": "政务外网业务区管理接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.34",
        "Device_name": "政务外网业务区管理接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.12",
        "Device_name": "互联网管理区管理接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.13",
        "Device_name": "互联网管理区管理接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.14",
        "Device_name": "互联网备份接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.15",
        "Device_name": "互联网备份接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.16",
        "Device_name": "互联网BMC接入交换机S5130（堆叠）",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.17",
        "Device_name": "互联网业务汇聚交换机S9850-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.18",
        "Device_name": "互联网业务汇聚交换机S9850-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.23",
        "Device_name": "互联网网络接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.24",
        "Device_name": "互联网网络接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.19",
        "Device_name": "互联网业务接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.20",
        "Device_name": "互联网业务接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.21",
        "Device_name": "互联网计算节点存储接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.22",
        "Device_name": "互联网计算节点存储接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.25",
        "Device_name": "互联网存储汇聚交换机S9850-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.26",
        "Device_name": "互联网存储汇聚交换机S9850-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.27",
        "Device_name": "互联网存储前端交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.28",
        "Device_name": "互联网存储前端交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.29",
        "Device_name": "互联网存储后端交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.30",
        "Device_name": "互联网存储后端交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.31",
        "Device_name": "互联网OBS接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.32",
        "Device_name": "互联网OBS接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.33",
        "Device_name": "互联网业务区管理接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.34",
        "Device_name": "互联网业务区管理接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.35",
        "Device_name": "互联网管理安全接入交换机S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.36",
        "Device_name": "互联网管理安全接入交换机S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.6",
        "Device_name": "政务外网安全资源池业务存储接入S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.100.7",
        "Device_name": "政务外网安全资源池业务存储接入S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.6",
        "Device_name": "互联网安全资源池业务存储接入S6805-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.100.7",
        "Device_name": "互联网安全资源池业务存储接入S6805-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.10",
        "Device_name": "政务外网管理汇聚交换机S9850-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.11",
        "Device_name": "政务外网管理汇聚交换机S9850-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "12.0.99.35",
        "Device_name": "政务外网BMC接入交换机S5130-3（堆叠）",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    # {
    #     "SWITCH_IP": "12.0.99.36",
    #     "Device_name": "政务外网OBS接入交换机S6805-3",
    #     "device_type": "hp_comware",
    #     "USERNAME": "h3c",
    #     "PASSWORD": "Wxxcy#$2025",
    #     "PORT": 22,
    # },
    # {
    #     "SWITCH_IP": "12.0.99.37",
    #     "Device_name": "政务外网OBS接入交换机S6805-4",
    #     "device_type": "hp_comware",
    #     "USERNAME": "h3c",
    #     "PASSWORD": "Wxxcy#$2025",
    #     "PORT": 22,
    # },
    {
        "SWITCH_IP": "11.0.99.10",
        "Device_name": "互联网管理汇聚交换机S9850-1",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.11",
        "Device_name": "互联网管理汇聚交换机S9850-2",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.38",
        "Device_name": "互联网BMC接入交换机S5130-3（堆叠）",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.39",
        "Device_name": "互联网OBS接入交换机S6805-3",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
    {
        "SWITCH_IP": "11.0.99.40",
        "Device_name": "互联网OBS接入交换机S6805-4",
        "device_type": "hp_comware",
        "USERNAME": "h3c",
        "PASSWORD": "Wxxcy#$2025",
        "PORT": 22,
    },
]